### ISSUE TITLE
Change permanent_cache's name

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#107]
Okay the first thing when @strager said when he saw the `permanent_cache` was him thinking that perminant here means perminant as in write it to the disk or something while perminent is meant as in it doesn't remove the old cache entries unless the user says while other caches (for example LRU) will remove the old caches.

So any ideas on a better name?

**Comment by strager** [comment]
non_evicting_cache

**Comment by the-moisrex** [comment]
> non_evicting_cache

A little mouthful but accurate from the technical point of view.
