### ISSUE TITLE
Basic JSON API

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#13]
Here we discuss the development of the JSON API regardless of the underlying implementation used.

We'll be working C++20 concepts to make this happen.

**Comment by looopTools** [comment]
> # Question!
> 
> Should `JSONValue` have `key()` and `value()` methods? The key and value are `JSONValue` after all. I think this should be `JSONObject`'s job!
> 
> I ask this because RapidJSON has `HasMember`, `AddMember` and others on `GenericValue` (and also on `GenericObject` but that's just for continence).
> 
> The thing is, they have to use `RAPIDJSON_ASSERT` and I don't like this kinda error handling (at least not today, maybe some other day I'd like it rofl ). ![image](https://user-images.githubusercontent.com/12122474/136760917-aeb1c5d3-8674-4fe5-be02-a95870ad3a7b.png)

It sounds reasonable to me to have it on `JSONValue`.
It is clean and puts the responsibility of providing this functionality closer to very the information is located.

**Comment by looopTools** [comment]
Just to be sure you mean getting the whole JSONObject as a user?

**Comment by the-moisrex** [comment]
Which library? RapidJSON or Web++? I don't think rapidjson provides such a thing. But Web++ is a web framework. Someday I even plan to write a package manager for it. Even [your query builder project](https://www.loooptools.com/c++/sql/development/2021/10/04/querycpp.html) needs to be implemented in this framework ([here](https://github.com/the-moisrex/webpp/tree/dev/core/include/webpp/db)) but those are their own issues.

And I'm writing C++ concepts before I just implement a wrapper around rapidjson because rapidjson is going to be just one implementation. Web++'s users should be able to switch between rapidjson, nlohmann, jsoncpp, or others. Each one would just need a wrapper to match these concepts here.

I'm doing the same kinda idea for other parts of the project. like logging:
![image](https://user-images.githubusercontent.com/12122474/136793082-c2d1de44-d2b4-4ff9-9475-c2a1f32cd4a2.png)

or server implementation (which uses `asio`, `posix`, `win32` and other ways, but I haven't had the time to finish any of them now):
![image](https://user-images.githubusercontent.com/12122474/136793236-f2e6c743-d0fc-47c4-aa14-3e479e34ad24.png)


So what do you think?

**Comment by the-moisrex** [comment]
Hmm; do you have any example in mind?

**Comment by looopTools** [comment]
I would prefer syntax for serialise.
```C++
  deserialize(JSONObject auto& obj) {
   user_id, username, emails = obj;
  }
```
 But yeah that is good

**Comment by looopTools** [comment]
I utterly hate option 1 because it looks like `std::array` and that has caused me more trouple with `is_same` that I care to admit. So I am biased

**Comment by the-moisrex** [comment]
What about these two?
```c++
  deserialize(JSONObject auto& obj) {
   user_id, username, emails = obj;
  }
```
vs.
```c++
  deserialize(json::object const& obj) {
   obj.deserialize(user_id, username, emails);
  }
```

Or maybe even both?

**Comment by the-moisrex** [comment]
I think it's nice to also have such thing:

```c++
field<string> username = "username";
field<int>      user_id     = "user_id";
field<json::array> emails = "emails";

username = "moisrex";
user_id = 313;
emails.emplace("test@example.com");

json::object user = (username, user_id, emails).as_object();
// or
doc.as_object().emplace(user);
```

**Comment by the-moisrex** [comment]
I think we've covered the basic features of a json library for now; the rest of the missing features and problems deserve an issue of their own. Thanks for contributing your time; closed.
