### ISSUE TITLE
consteval ipv4::create(...)

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#351]
The `ipv4` (and `ipv6`) classes are constexpr friendly, but this kinda code MIGHT be parsed at run-time while it can be run at compile-time too:

```c++
if (ip == ipv4{"127.1.1.1"}) { ... }
```

I would like `ipv4::create` that just **constructs** `ipv4`, but it's **consteval** so the string in `ipv4::create("127.0.0.1")` will be parsed at compile-time.

**Comment by Sienq** [comment]
Can you please provide more detailed info about this feature req?

**Comment by the-moisrex** [comment]
> Can you please provide more detailed info about this feature req?

I updated the descriptions above.

**Comment by HSienkiewicz** [comment]
So is that sum up to adding create method(which is consteval) and it just invokes constructor of ipv4?

**Comment by Sienq** [comment]
So is that basically sums up to adding consteval create function which just invokes constructor?

**Comment by the-moisrex** [comment]
Yep 😊

**Comment by Sienq** [comment]
Nice 👍. I will try to take care of that as well as version for ipv6

**Comment by the-moisrex** [comment]
I'd appreciate it.

**Comment by the-moisrex** [comment]
Made `ipv4::invalid` and `ipv6::invalid` consteval as well, I did also remove the "explicit"ness of the string constructors; I'm not sure where or when I added that and whether or not that's gonna be a problem! The tests are passing though! at least ip-related ones.
